version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: server_development
    ports:
      - 3306:3306
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: ./back
    command: bash -c "rm -f tmp/pids/server.pid && bundle install  && foreman start -f procfile.dev"
    user: root
    volumes:
      - ./back:/back
    ports:
      - '3001:3000'
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
    stdin_open: true
    tty: true
  web:
    build: ./front
    command: npm run dev
    tty: true
    volumes:
      - ./front:/nextjs
    ports:
      - '3000:3000'
volumes:
  mysql-data:
    driver: local
